name: Danger

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger against PR"
    container: docker://ghcr.io/danger/danger-kotlin:1.0.0-beta.2

    steps:
      - uses: actions/checkout@v2
      - name: Build & Install Plugin on Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
          ORG_GRADLE_PROJECT_signingKeyId: '${{ secrets.GPG_SIGNING_KEY_ID }}'
          ORG_GRADLE_PROJECT_signingKey: '${{ secrets.GPG_SIGNING_KEY }}'
          ORG_GRADLE_PROJECT_signingPassword: '${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}'
        run:
          ./gradlew build installDangerPlugin
      - name: Run danger/kotlin against PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
          ORG_GRADLE_PROJECT_signingKeyId: '${{ secrets.GPG_SIGNING_KEY_ID }}'
          ORG_GRADLE_PROJECT_signingKey: '${{ secrets.GPG_SIGNING_KEY }}'
          ORG_GRADLE_PROJECT_signingPassword: '${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}'
        run:
          danger-kotlin ci --failOnErrors --dangerfile=danger/Dangerfile.df.kts

