name: Danger

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Tests"

    steps:
      - uses: actions/checkout@v2

      - name: Run Unit Tests
        run:
          ./gradlew test

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
